[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python3 -m gunicorn app:app --bind 0.0.0.0:$PORT"
